services:
  - type: web
    name: dressapp-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 